site_name: FusionReactor Documentation
site_url: https://intergral.github.io/frdocs/
repo_name: frdocs
repo_url: https://github.com/intergral/frdocs
repo_url: https://github.com/intergral/frdocs
edit_uri: edit/master/docs/docs


theme:
  name: material
  favicon: images/FRAtom_White.svg
  logo: images/FRAtom_White.svg
  features:
    - navigation.sections
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  font:  
    text: 'Roboto'
    code: 'monospace'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mod

nav:
  - Home: index.md
  - GETTING STARTED: 
     - Introduction to FusionReactor: Getting-started/intro-to-fr.md
     - Install FusionReactor:  Getting-started/install-fr.md
     - Tutorials & walkthroughs: 
        - Get to know the UI: Getting-started/Tutorials/know-the-ui.md
        - Create a dashboard: Getting-started/Tutorials/create-dashboard.md
        - Troubleshooting:
           - todo.md
  - HOW TO CONTRIBUTE:
           - Contribute/how-to-contribute.md
           - Style Guide:
              - Overview: Contribute/style-guide/overview.md
              - Images: Contribute/style-guide/images.md
              - Language & grammar: 
                  - Abbreviations: Contribute/style-guide/Language-and-grammar/Abbreviations.md
                  - Capitalization: Contribute/style-guide/Language-and-grammar/Capitalization.md
                  - Contractions: Contribute/style-guide/Language-and-grammar/Contractions.md
                  - Formatting: Contribute/style-guide/Language-and-grammar/Formatting.md
  - MONITOR YOUR DATA:
     - Best Practices:      
           - Overview: Best-Practices/Installation/installation-overview.md
           - Local server:
              - ColdFusion & databases: Best-Practices/Installation/CF-guide.md
              - Java/Lucee & databases: Best-Practices/Installation/Lucee-Java-guide.md
              - Java/Lucee, databases & other languages: Best-Practices/Installation/Java-Lucee-OTel.md
           - Scripted: 
              - Java/CFML & databases: Best-Practices/Installation/scripted1.md
              - Java/CFML, databases & other languages: Best-Practices/Installation/scripted2.md
              - Databases & other languages: Best-Practices/Installation/scripted3.md
           - Docker:
              - Java/CFML & databases: Best-Practices/Installation/FR-ObsAgent.md
              - Java/CFML, databases & other languages: Best-Practices/Installation/FR-ObsAgent-OTel.md
              - Databases & other languages: Best-Practices/Installation/ObsAgent-OTel.md
     - FusionReactor Agent:
        - Overview: Monitor-your-data/FR-Agent/agent-overview.md
        - Install: 
           - Automatic: Monitor-your-data/FR-Agent/Installation/Automatic.md
           - FRAM: Monitor-your-data/FR-Agent/Installation/FRAM.md  
           - Manual: 
                - Install: Monitor-your-data/FR-Agent/Installation/Manual.md
                - Configuration examples: Monitor-your-data/FR-Agent/Installation/Configuration-examples.md
                - More:
                    - Download links: Monitor-your-data/FR-Agent/Installation/Download-Links.md
                    - MD5s: Monitor-your-data/FR-Agent/Installation/md5.md
           - Docker: Monitor-your-data/FR-Agent/Installation/Docker.md         
           - CommandBox: Monitor-your-data/FR-Agent/Installation/CommandBox.md
        - Upgrade:
           - Automatic: Monitor-your-data/FR-Agent/Upgrade/Auto-upgrade.md
           - Manual: Monitor-your-data/FR-Agent/Upgrade/Manual-upgrade.md
           - Docker: Monitor-your-data/FR-Agent/Upgrade/upgrade-docker.md
           - CommandBox: Monitor-your-data/FR-Agent/Upgrade/upgrade-commandbox.md
        - Uninstall:
           - FRAM: Monitor-your-data/FR-Agent/Uninstall/FRAMdeactivate.md
           - Manual: Monitor-your-data/FR-Agent/Uninstall/MANdeactivate.md
        - More:
           - Compatibility & requirements: Monitor-your-data/FR-Agent/More/requirements.md
           - Configuration: Monitor-your-data/FR-Agent/More/FusionReactor-Agent-Shipper.md
           - Distributed tracing: 
               - Distributed-Tracing/attributes.md
               - Distributed-Tracing/propagators.md
               - Distributed-Tracing/sampling.md
               - Distributed-Tracing/exporting.md
               - Distributed-Tracing/span-lifecycle.md
               - Distributed-Tracing/linkage-in-grafana.md
        - FAQs & troubleshooting: todo.md
     - Observability Agent:
        - Overview: Monitor-your-data/Observability-agent/overview.md
        - Install:
           - FRAM: Monitor-your-data/Observability-agent/Installation/FRAM.md
           - Local install using code snippets: Monitor-your-data/Observability-agent/Installation/Snippets.md
           - Docker: Monitor-your-data/Observability-agent/Installation/Docker.md
        - Configuration: Monitor-your-data/Observability-agent/Configuration.md
        - Ingesting data into FR: Monitor-your-data/Observability-agent/Ingest.md
     - OpenTelemetry:
       - Getting started: Monitor-your-data/OpenTelemetry/getting-started.md
       - Instrumentation guides:
         - Overview: Monitor-your-data/OpenTelemetry/Instrumentation/Overview.md
         - C++: Monitor-your-data/OpenTelemetry/Instrumentation/Cpp.md
      #  - .NET: Cloud/OpenTelemetry/NET.md
         - Go: Monitor-your-data/OpenTelemetry/Instrumentation/Go.md
         - Python: Monitor-your-data/OpenTelemetry/Instrumentation/Python.md
       - Shipping data to FR:
         - Overview: Monitor-your-data/OpenTelemetry/Shipping/overview.md
         - OpenTelemetry Collector: Monitor-your-data/OpenTelemetry/Shipping/Collector.md
         - Observability Agent: Monitor-your-data/OpenTelemetry/Shipping/Observability-agent.md
         - Grafana Alloy: Monitor-your-data/OpenTelemetry/Shipping/Grafana-agent.md
     #Cloud/OpenTelemetry/OTel-shipping.md
       - Visualize your data:
         - Metrics: Monitor-your-data/OpenTelemetry/Visualize/Metrics.md
         - Traces: Monitor-your-data/OpenTelemetry/Visualize/Traces.md
         - Logs: Monitor-your-data/OpenTelemetry/Visualize/Logs.md
         - Distributed tracing: Monitor-your-data/OpenTelemetry/Visualize/Distributed-tracing.md
     - Kubernetes monitoring:
        - Overview: Monitor-your-data/Kubernetes-monitoring/overview.md
        - Shipping K8s data to FR: Monitor-your-data/Kubernetes-monitoring/Shipping.md
     - Log monitoring:
        - Overview: Monitor-your-data/Log-monitoring/overview.md
        - Log shipper: Monitor-your-data/Log-monitoring/log-shipper.md
        - FR Agent shipper: Monitor-your-data/Log-monitoring/agent-shipper.md
        - Alerting: Monitor-your-data/Log-monitoring/alerting.md
        - Labels & fields: Monitor-your-data/Log-monitoring/labels-and-fields.md
  - DATA INSIGHTS: 
       # - Data-insights/Features/account.md
        - Alerting: Data-insights/Features/alerting.md
        - Anomaly Detection:
            - Overview: Data-insights/Features/Anomaly-Detection/ADoverview.md
            - User guide: Data-insights/Features/Anomaly-Detection/ADuserguide.md
        - Applications: Data-insights/Features/applications.md
        - Crash Protection:
            - todo.md
        - Dashboards: Data-insights/Features/dashboards.md
        - Debugger:
            - todo.md
        - Deep: 
            - todo.md
        - Enterprise Dashboard:
            - todo.md
        - Explore: Data-insights/Features/explore.md
        - Historic data: Data-insights/Features/timepicker.md
        - On-Prem UI:
            - CPU Sampler:
              - todo.md
            - Crash Protection:
              - todo.md
            - Debugger:
              - todo.md
            - Enterprise Dashboard:
              - todo.md
            - JDBC:
              - todo.md
            - Logs:
                - todo.md
               # - Data-insights/Features/Onprem-UI/Logs/Importing-and-Graphing-Data-in-Excel.md
                #- Data-insights/Features/Onprem-UI/Logs/Logs.md
                #- Data-insights/Features/Onprem-UI/Logs/Log-Archives.md
                #- Data-insights/Features/Onprem-UI/Logs/Log-Archive-Viewer.md
                #- Data-insights/Features/Onprem-UI/Logs/Cloud-Settings.md
               # - Data-insights/Features/Onprem-UI/Logs/Cloud-Log-Obfuscation-Rules.md
                #- Data-insights/Features/Onprem-UI/Logs/Cloud-Log-MultiLine-Blocks.md
               # - Data-insights/Features/Onprem-UI/Logs/Settings.md
                #- Files:
                 # - Data-insights/Features/Onprem-UI/Logs/Memory-Logs.md
                  #- Data-insights/Features/Onprem-UI/Logs/Files/Class-Loading-Log.md
                 # - Data-insights/Features/Onprem-UI/Logs/Files/Cloud-State-Log.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/CPU-Thread-Log.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/Crash-Protection-Log.md
                 # - Data-insights/Features/Onprem-UI/Logs/Files/Device-Log.md
                  #- Data-insights/Features/Onprem-UI/Logs/Files/Garbage-Collection-Logs.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/Instance-Manager-Log.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/JDBC-Log.md
                # - Data-insights/Features/Onprem-UI/Logs/Files/Notification-Log.md
              # - Data-insights/Features/Onprem-UI/Logs/Files/Reactor-Log.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/Request-Log.md
                 # - Data-insights/Features/Onprem-UI/Logs/Files/Resource-Log.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/Stdout.log-and-Stderr.log.md
                #  - Data-insights/Features/Onprem-UI/Logs/Files/Thread-State-Log.md
            - Memory:
              - todo.md
            - Metrics:
              - todo.md
            - Profiler:
              - todo.md
            - Requests:
              - todo.md
            - Resources: 
              - todo.md
            - System Resources:
              - todo.md
            - Transactions:
              - todo.md
            - UEM Sessions:
              - todo.md
        - OpsPilot:
            - OpsPilot Assistant:
              - Overview: Data-insights/Features/OpsPilot/AIoverview.md
            - OpsPilot Integrations:
              - Overview: Data-insights/Features/OpsPilot/OpsPilot-Hub/integrations-overview.md
            - OpsPilot Hub: 
              - Overview: Data-insights/Features/OpsPilot/OpsPilot-Hub/overview.md 
              - Assistant:
                - User guide: Data-insights/Features/OpsPilot/OpsPilot-user-guide.md
              - Services: Data-insights/Features/OpsPilot/OpsPilot-Hub/Services.md
              - Knowledge: Data-insights/Features/OpsPilot/OpsPilot-Hub/Knowledge.md
              - Integrations:
                - Jira: Data-insights/Features/OpsPilot/OpsPilot-Hub/Jira.md
                - Microsoft Teams: Data-insights/Features/OpsPilot/OpsPilot-Hub/Teams.md
                - Slack: Data-insights/Features/OpsPilot/OpsPilot-Hub/Slack.md
        - Profiler:
            - todo.md
        - Servers: Data-insights/Features/servers.md
  - LATEST UPDATES: 
     - What's new: 
        - todo.md
     - Releases: 
          - todo.md
  - ADMIN & DATA:
     - Account & user management: 
        - todo.md
     - Data: 
        - todo.md
     - Security: 
        - todo.md
     - Licenses: 
        - todo.md

plugins:
  - glightbox
  - search
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

copyright: '<a href="https://intergral.com" target="_blank">Copyright Â© 2024 Intergral GmbH. All rights reserved.</a>'